### PR TITLE
Extension methods & Custom Doc routes, names, descriptions

### PR DESCRIPTION
**Pull request by davelovesoftware**
Hey! Love this lib. Figured I'd contribute some minor improvements that I noticed I wanted.

1) Extension methods.
Just looks cleaner, no? But I changed two of the method names in the process to make it clear this is configuring versioning. I left the original method names in as non-extension methods but marked obsolete for backwards compatibility.

2) Custom doc routes, names, and descriptions.
I wanted to move all my api docs to "/docs" but couldn't, also I wanted to display slightly more descriptive doc names. This would allow that customization and I think it's still pretty clean.

### CODE REVIEW

**Comment by rh072005** [comment]
Cheers for the love. 
Totally agree that extension methods are clearer. 
I've also been considering the custom routes so you've saved me some work there :smile: 
What I'm gong to do is create a new branch and merge this PR into it just to udpate README to reflect the changes and add some additional test coverage for the custom routes.

**Comment by rh072005** [comment]
I've completed the additional changes in the extensions-and-custom-routes branch if you want to take a look @bungeemonkee. If you're happy with everything I'll get it merged and shipped

**Comment by davelovesoftware** [comment]
@rh072005 Thanks for taking the input. I looked at your updates and it all makes perfect sense to me. :)

**Comment by rh072005** [comment]
@bungeemonkee Cool, 0.5.0-pre is now up on MyGet and NuGet. Thanks for your help

**Pull request merged**
